### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.steve_md.smartmkulima.ShambaApp" on path: DexPathList[[zip file "/data/app/~~Oo2QJNclpNfV-wR-pfj0pQ==/com.steve_md.smartmkulima-PddnuguhXN1Ouqbo6A_ZHA==

### ISSUE THREAD

**Issue by MuindiStephen** [MuindiStephen/Shamba-App#37]
E/AndroidRuntime( 7368): Process: com.steve_md.smartmkulima, PID: 7368
E/AndroidRuntime( 7368): java.lang.RuntimeException: Unable to instantiate application com.steve_md.smartmkulima.ShambaApp package com.steve_md.smartmkulima: java.lang.ClassNotFoundException: Didn't find class "com.steve_md.smartmkulima.ShambaApp" on path: DexPathList[[zip file "/data/app/~~Oo2QJNclpNfV-wR-pfj0pQ==/com.steve_md.smartmkulima-PddnuguhXN1Ouqbo6A_ZHA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Oo2QJNclpNfV-wR-pfj0pQ==/com.steve_md.smartmkulima-PddnuguhXN1Ouqbo6A_ZHA==/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 7368): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
E/AndroidRuntime( 7368): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
E/AndroidRuntime( 7368): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6720)
E/AndroidRuntime( 7368): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
E/AndroidRuntime( 7368): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
E/AndroidRuntime( 7368): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7368): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 7368): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 7368): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 7368): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7368): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 7368): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 7368): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.steve_md.smartmkulima.ShambaApp" on path: DexPathList[[zip file "/data/app/~~Oo2QJNclpNfV-wR-pfj0pQ==/com.steve_md.smartmkulima-PddnuguhXN1Ouqbo6A_ZHA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Oo2QJNclpNfV-wR-pfj0pQ==/com.steve_md.smartmkulima-PddnuguhXN1Ouqbo6A_ZHA==/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 7368): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime( 7368): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 7368): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 7368): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
E/AndroidRuntime( 7368): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51)
E/AndroidRuntime( 7368): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1243)
E/AndroidRuntime( 7368): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
E/AndroidRuntime( 7368): 	... 11 more
E/AndroidRuntime( 7368): 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/steve_md/smartmkulima/Hilt_ShambaApp;
E/AndroidRuntime( 7368): 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime( 7368): 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime( 7368): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime( 7368): 		... 16 more
E/AndroidRuntime( 7368): 	Caused by: java.lang.ClassNotFoundException: Didn't find class "com.steve_md.smartmkulima.Hilt_ShambaApp" on path: DexPathList[[zip file "/data/app/~~Oo2QJNclpNfV-wR-pfj0pQ==/com.steve_md.smartmkulima-PddnuguhXN1Ouqbo6A_ZHA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Oo2QJNclpNfV-wR-pfj0pQ==/com.steve_md.smartmkulima-PddnuguhXN1Ouqbo6A_ZHA==/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 7368): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime( 7368): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 7368): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by MuindiStephen** [comment]
fixed.
